global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend-go'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'rust-sfu'
    static_configs:
      - targets: ['rust-sfu:3030']
